name: hyprland
title: hyprland
summary: Tiling compositor with the looks
license: BSD-3-Clause
adopt-info: hyprland
description: |
  Tiling compositor with the looks

base: core24
confinement: classic

apps:
  hyprland:
    command: usr/bin/Hyprland
  hyprctl:
    command: usr/bin/hyprctl
  hyprpm:
    command: usr/bin/hyprpm

parts:
  hyprlang:
    source: https://github.com/hyprwm/hyprlang
    source-tag: v0.5.2
    source-type: git
    plugin: cmake
    build-attributes:
      - enable-patchelf
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_BUILD_TYPE:STRING=Release

  hyprutils:
    source: https://github.com/hyprwm/hyprutils
    source-tag: v0.2.0
    source-type: git
    plugin: cmake
    build-attributes:
      - enable-patchelf
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_BUILD_TYPE:STRING=Release

  hyprwayland-scanner:
    source: https://github.com/hyprwm/hyprwayland-scanner
    source-tag: v0.4.0
    source-type: git
    plugin: cmake
    build-attributes:
      - enable-patchelf
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    build-packages:
      - libpugixml-dev
    stage-packages:
      - libpugixml-dev

  hyprcursor:
    after: 
    - hyprlang
    source: https://github.com/hyprwm/hyprcursor
    source-tag: v0.1.9
    source-type: git
    plugin: cmake
    build-attributes:
      - enable-patchelf
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_BUILD_TYPE:STRING=Release
    build-packages:
      - libzip-dev
      - librsvg2-dev
      - libtomlplusplus-dev
    stage-packages:
      - libzip-dev
      - librsvg2-dev
      - libtomlplusplus-dev

  libxcb-errors:
    source: https://gitlab.freedesktop.org/xorg/lib/libxcb-errors.git
    source-tag: xcb-util-errors-1.0.1
    source-type: git
    plugin: autotools
    build-attributes:
      - enable-patchelf
    build-packages:
      - xcb-proto
      - xutils-dev

  # Ubuntu package doesn't include tablet-v2.xml
  wayland-protocols:
    source: https://gitlab.freedesktop.org/wayland/wayland-protocols.git
    source-tag: '1.36'
    source-type: git
    plugin: meson
    build-attributes:
      - enable-patchelf
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release

  hyprland:
    after:
      - hyprcursor
      - hyprlang
      - hyprutils
      - hyprwayland-scanner
      - libxcb-errors
      - wayland-protocols
    source: https://github.com/hyprwm/Hyprland
    source-tag: v0.41.2
    source-type: git
    plugin: cmake
    cmake-generator: Ninja
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX:PATH=/usr
      - -DCMAKE_BUILD_TYPE:STRING=Release
    build-attributes:
      - enable-patchelf
    build-packages:
      - build-essential
      - cmake
      - cmake-extras
      - fontconfig
      - gettext
      - gettext-base
      - glslang-tools
      - hwdata
      - libavcodec-dev
      - libavformat-dev
      - libavutil-dev
      - libdisplay-info-dev
      - libdrm-dev
      - libegl-dev
      - libegl1-mesa-dev
      - libffi-dev
      - libfontconfig-dev
      - libgbm-dev
      - libgles2
      - libgulkan-dev
      - libinput-bin
      - libinput-dev
      - libliftoff-dev
      - libpango1.0-dev
      - libpangocairo-1.0-0
      - libpixman-1-dev
      - libseat-dev
      - libudev-dev
      - libvkfft-dev
      - libvulkan-dev
      - libvulkan-volk-dev
      - libwayland-dev
      - libxcb-composite0-dev
      - libxcb-dri3-dev
      - libxcb-ewmh-dev
      - libxcb-ewmh2
      - libxcb-icccm4-dev
      - libxcb-present-dev
      - libxcb-render-util0-dev
      - libxcb-res0-dev
      - libxcb-util-dev
      - libxcb-xinput-dev
      - libxkbcommon-dev
      - libxkbcommon-x11-dev
      - libxkbregistry-dev
      - libxml2-dev
      - meson
      - ninja-build
      - seatd
      - vulkan-validationlayers
      - wget
      - xdg-desktop-portal-wlr
      - xwayland
    stage-packages:
      - libdisplay-info-dev
      - libegl-dev
      - libegl1-mesa-dev
      - libgbm-dev
      - libinput-dev
      - libliftoff-dev
      - libseat-dev
      - libwayland-dev
      - libxcb-composite0-dev
      - libxcb-icccm4-dev
      - libxcb-res0-dev
    override-pull: |
      craftctl default
      craftctl set version=$(git describe --tags | sed 's/v//')
    override-stage: |
      craftctl default
      sed -i "s/Exec=Hyprland/Exec=hyprland/" usr/share/wayland-sessions/hyprland.desktop
